### ISSUE TITLE
Isolation and JSON

### ISSUE THREAD

**Issue by joeyhub** [eight04/rollup-plugin-cjs-es#16] opened 2019-09-11 12:17 UTC
Does this try to build everything in node_modules?

I'm getting errors on things where I have no idea how they would have gotten into the dependency tree since they're not imported.

It also produces a syntax error trying to parse a JSON include (which makes questionable sense as JSON is valid JS and the file looks file).

**Comment by leeoniya** [comment] 2019-09-11 12:41
RE: JSON, see https://github.com/eight04/rollup-plugin-cjs-es/issues/9

**Comment by eight04** [comment] 2019-09-11 13:39
> Does this try to build everything in node_modules?

This plugin transforms all files by default. If you want to specify which file should be transformed, you can use the `include` option:
https://github.com/eight04/rollup-plugin-cjs-es#api

However, I suggest scanning all files so the plugin can collect the export type of each module to avoid export type mismatch.

> I'm getting errors on things where I have no idea how they would have gotten into the dependency tree since they're not imported.

Try the [analyzer](https://github.com/doesdev/rollup-plugin-analyzer) plugin. Use it to find out why the file is included.

> It also produces a syntax error trying to parse a JSON include

This happens when cjs-es tries to parse a JSON file. You have two options:

1. Exclude JSON files for cjs-es.
    ```js
    cjs({
      exclude: ["**/*.json"]
    })
    ```
2. Put the json plugin before cjs-es just like #9.

> JSON is valid JS

JSON is not valid JS when starting with the `{` symbol. You can try saving `{"a":"b"}` as a js file and execute it with node.

**Comment by joeyhub** [comment] 2019-09-12 15:21
So basically your build target should have its own node_modules as it wont just traverse the dependency tree.

JSON is handled by an additional plugin.

**Comment by eight04** [comment] 2019-09-13 03:58
> So basically your build target should have its own node_modules as it wont just traverse the dependency tree.

I didn't get the context. Can you elaborate?

> JSON is handled by an additional plugin.

Yes.

**Comment by joeyhub** [comment] 2019-09-13 11:26
I just have one big node_modules in my entry point. If it processes all packages then it'll pick up a whole bunch of stuff and noise from things not relevant to what it's building dependency treewise which at the very least means erupting an inordinate amount of warns.

If it's not meant to do that then it might be a clash of the plugins. I switched to commonjs and that does some things like it seems to block the babel plugin from running on its imports (possibly either by bad flow or missed default option). I'm not sure all plugins play nice.

**Comment by eight04** [comment] 2019-09-13 12:34
> I just have one big node_modules in my entry point.

* If you mean that your `rollup.config.js` looks like this:
    ```js
    export {
      input: [
        "src/index.js", "node_modules/lib/somefile.js"
      ],
      ...
    }
    ```
    Then you are probably doing something wrong.

* If you mean that your entry point e.g. `src/index.js` contains something like this:
    ```js
    const Vue = require("vue"); // this is a large dependency
    ...
    ```
    And you don't want to include the large dependency in the bundle, you should add `vue` to `options.external` array:
    https://rollupjs.org/guide/en/#external

    If you are targeting web and the dependency is a pre-built bundle that can be accessed through a global variable, try external-globals plugin:
    https://www.npmjs.com/package/rollup-plugin-external-globals

> If it processes all packages then it'll pick up a whole bunch of stuff

Rollup only process files that are imported. For example:
*index.js*
```js
import foo from "./foo.js";
console.log(foo);
```
*foo.js*
```js
export default "FOO";
```
*bar.js*
```js
export default "BAR";
```
Use `index.js` as the entry point then `index.js` and `foo.js` will be included in the bundle.

**Comment by joeyhub** [comment] 2019-09-13 14:36
> This plugin transforms all files by default.

This is the confusing bit, I assume you mean all files in the dependency graph by default unless specified?

**Comment by eight04** [comment] 2019-09-13 15:13
Yes. Most plugins work on imported files only e.g. cjs-es, babel. Some plugins work on finalized bundles e.g. uglify, terser. Some plugins may load extra dependencies e.g. inline-js.

If you didn't require or import the large dependency in your source code, it might be caused by a plugin. You can post your config file here so we can help.

**Closed as completed** 2019-10-13 11:23 UTC
